solution = [99, 105, 103, 97, 114]
salt = "2242483025063691345886162469165300238"
commitment = "0x27df16ca6c5343937f467d04bb5d7408914b2d2d835a0eb28391c500e1ac4ed3"
guess = [99, 114, 97, 110, 101]
clue = [2, 1, 1, 0, 0]
clue_packed = "592"
