solution = [98, 105, 98, 108, 101]
salt = "94987380753092549624318320790396663568"
commitment = "0x0384505a870e97fd7524a28b55c98ed4cde49b17f14c746cb12fa81408f62a4d"
guess = [116, 97, 98, 108, 101]
clue = [0, 0, 2, 2, 2]
clue_packed = "42"
